allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://android-sdk.is.com/" }
        maven { url "https://artifact.bytedance.com/repository/pangle/" }
        maven { url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea" }
        maven { url 'https://artifacts.applovin.com/android' }
    }
}

rootProject.buildDir = "../build"
subprojects {
    if (project.projectDir.path.startsWith(rootProject.projectDir.parentFile.path)) {
        project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
